services:
  client:
    container_name: pandasbi-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always   
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
